# Generated by Django 5.2 on 2025-04-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reporter_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter_phone',
            field=models.CharField(max_length=20),
        ),
    ]
